appName: component-app
logLevel: WARN

app:
  init:
    create_tables: false

databases:
  mssql:
    host: localhost
    username: librarian
    password: test1234
    database: altium_db
    driver: SQL+Server+Native+Client+11.0