DROP TABLE IF EXISTS t_EmbeddedMicrocontrollers;

CREATE TABLE t_EmbeddedMicrocontrollers
(
    `supplier4`                 VARCHAR(100) DEFAULT NULL,
    `supplier4partno`           VARCHAR(150) DEFAULT NULL,
    `supplier5`                 VARCHAR(100) DEFAULT NULL,
    `supplier5partno`           VARCHAR(150) DEFAULT NULL,
    `supplier6`                 VARCHAR(100) DEFAULT NULL,
    `supplier6partno`           VARCHAR(150) DEFAULT NULL,
    `componentlink1description` VARCHAR(100) DEFAULT NULL,
    `componentlink1url`         VARCHAR(250) DEFAULT NULL,
    `componentlink2description` VARCHAR(100) DEFAULT NULL,
    `supplier3partno`           VARCHAR(150) DEFAULT NULL,
    `componentlink2url`         VARCHAR(250) DEFAULT NULL,
    `componentlink3url`         VARCHAR(250) DEFAULT NULL,
    `componentlink4description` VARCHAR(100) DEFAULT NULL,
    `componentlink4url`         VARCHAR(250) DEFAULT NULL,
    `componentlink5description` VARCHAR(100) DEFAULT NULL,
    `componentlink5url`         VARCHAR(250) DEFAULT NULL,
    `componentlink6description` VARCHAR(100) DEFAULT NULL,
    `componentlink6url`         VARCHAR(250) DEFAULT NULL,
    `footprintpath2`            VARCHAR(100) DEFAULT NULL,
    `footprintref2`             VARCHAR(100) DEFAULT NULL,
    `componentlink3description` VARCHAR(100) DEFAULT NULL,
    `footprintpath3`            VARCHAR(100) DEFAULT NULL,
    `supplier3`                 VARCHAR(100) DEFAULT NULL,
    `supplier2`                 VARCHAR(100) DEFAULT NULL,
    `lastupdated`               DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `archived`                  BIT          DEFAULT 0,
    `value`                     VARCHAR(100) DEFAULT NULL,
    `comment`                   VARCHAR(100) DEFAULT NULL,
    `manufacturerpartno`        VARCHAR(100) NOT NULL,
    `manufacturer`              VARCHAR(100) NOT NULL,
    `description`               VARCHAR(200) DEFAULT NULL,
    `price`                     VARCHAR(100) DEFAULT NULL,
    `lifecycle`                 VARCHAR(100) DEFAULT NULL,
    `supplier2partno`           VARCHAR(150) DEFAULT NULL,
    `series`                    VARCHAR(100) DEFAULT NULL,
    `footprintpath`             VARCHAR(100) DEFAULT NULL,
    `symbolref`                 VARCHAR(100) DEFAULT NULL,
    `symbolpath`                VARCHAR(100) DEFAULT NULL,
    `devicepackage`             VARCHAR(100) DEFAULT NULL,
    `type`                      VARCHAR(100) DEFAULT NULL,
    `packaging`                 VARCHAR(100) DEFAULT NULL,
    `minimumorder`              INT          DEFAULT 0,
    `supplier1`                 VARCHAR(100) DEFAULT NULL,
    `supplier1partno`           VARCHAR(150) DEFAULT NULL,
    `footprintref`              VARCHAR(100) DEFAULT NULL,
    `footprintref3`             VARCHAR(100) DEFAULT NULL,
    `Connectivity`              VARCHAR(127) DEFAULT NULL,
    `RAMSize`                   VARCHAR(127) DEFAULT NULL,
    `EEPROMSize`                VARCHAR(127) DEFAULT NULL,
    `ProgramMemoryType`         VARCHAR(127) DEFAULT NULL,
    `ProgramMemorySize`         VARCHAR(127) DEFAULT NULL,
    `NumberofIO`                VARCHAR(127) DEFAULT NULL,
    `Peripherals`               VARCHAR(127) DEFAULT NULL,
    `OscillatorType`            VARCHAR(127) DEFAULT NULL,
    `Speed`                     VARCHAR(127) DEFAULT NULL,
    `CoreSize`                  VARCHAR(127) DEFAULT NULL,
    `CoreProcessor`             VARCHAR(127) DEFAULT NULL,
    `SupplierDevicePackage`     VARCHAR(127) DEFAULT NULL,
    `PackageCase`               VARCHAR(127) DEFAULT NULL,
    `OperatingTemperature`      VARCHAR(127) DEFAULT NULL,
    `MountingType`              VARCHAR(127) DEFAULT NULL,
    `PartStatus`                VARCHAR(127) DEFAULT NULL,
    `VoltageSupplyVccVdd`       VARCHAR(127) DEFAULT NULL,
    `DataConverters`            VARCHAR(127) DEFAULT NULL,
    INDEX (`lastupdated`),
    INDEX (`archived`),
    INDEX (`manufacturerpartno`),
    PRIMARY KEY (`manufacturerpartno`,
                 `manufacturer`)
) CHARACTER SET utf16
  COLLATE utf16_general_ci;


DROP VIEW IF EXISTS EmbeddedMicrocontrollers;

CREATE VIEW EmbeddedMicrocontrollers AS
SELECT `comment`                   AS `Comment`,
       `componentlink1description` AS `ComponentLink1Description`,
       `componentlink1url`         AS `ComponentLink1URL`,
       `componentlink2description` AS `ComponentLink2Description`,
       `componentlink2url`         AS `ComponentLink2URL`,
       `componentlink3description` AS `ComponentLink3Description`,
       `componentlink3url`         AS `ComponentLink3URL`,
       `componentlink4description` AS `ComponentLink4Description`,
       `componentlink4url`         AS `ComponentLink4URL`,
       `componentlink5description` AS `ComponentLink5Description`,
       `componentlink5url`         AS `ComponentLink5URL`,
       `componentlink6description` AS `ComponentLink6Description`,
       `componentlink6url`         AS `ComponentLink6URL`,
       `Connectivity`              AS `Connectivity`,
       `CoreProcessor`             AS `Core Processor`,
       `CoreSize`                  AS `Core Size`,
       `DataConverters`            AS `Data Converters`,
       `description`               AS `Description`,
       `devicepackage`             AS `Device Package`,
       `EEPROMSize`                AS `EEPROM Size`,
       `footprintpath`             AS `Footprint Path`,
       `footprintpath2`            AS `Footprint Path 2`,
       `footprintpath3`            AS `Footprint Path 3`,
       `footprintref`              AS `Footprint Ref`,
       `footprintref2`             AS `Footprint Ref 2`,
       `footprintref3`             AS `Footprint Ref 3`,
       `lastupdated`               AS `LastUpdated`,
       `lifecycle`                 AS `Lifecycle Status`,
       `manufacturer`              AS `Manufacturer`,
       `manufacturerpartno`        AS `Part Number`,
       `minimumorder`              AS `Minimum Order`,
       `MountingType`              AS `Mounting Type`,
       `NumberofIO`                AS `Number of I/O`,
       `OperatingTemperature`      AS `Operating Temperature`,
       `OscillatorType`            AS `Oscillator Type`,
       `PackageCase`               AS `Package / Case`,
       `packaging`                 AS `Packaging`,
       `PartStatus`                AS `Part Status`,
       `Peripherals`               AS `Peripherals`,
       `price`                     AS `Price`,
       `ProgramMemorySize`         AS `Program Memory Size`,
       `ProgramMemoryType`         AS `Program Memory Type`,
       `RAMSize`                   AS `RAM Size`,
       `series`                    AS `Series`,
       `Speed`                     AS `Speed`,
       `supplier1`                 AS `Supplier 1`,
       `supplier1partno`           AS `Supplier Part Number 1`,
       `supplier2`                 AS `Supplier 2`,
       `supplier2partno`           AS `Supplier Part Number 2`,
       `supplier3`                 AS `Supplier 3`,
       `supplier3partno`           AS `Supplier Part Number 3`,
       `supplier4`                 AS `Supplier 4`,
       `supplier4partno`           AS `Supplier Part Number 4`,
       `supplier5`                 AS `Supplier 5`,
       `supplier5partno`           AS `Supplier Part Number 5`,
       `supplier6`                 AS `Supplier 6`,
       `supplier6partno`           AS `Supplier Part Number 6`,
       `SupplierDevicePackage`     AS `Supplier Device Package`,
       `symbolpath`                AS `Library Path`,
       `symbolref`                 AS `Library Ref`,
       `type`                      AS `Type`,
       `value`                     AS `Value`,
       `VoltageSupplyVccVdd`       AS `Voltage - Supply (Vcc/Vdd)`
FROM t_EmbeddedMicrocontrollers t;
