DROP TABLE IF EXISTS t_MOSFET_Discrete;

create table t_MOSFET_Discrete
(
    `supplier4`                    VARCHAR(100) DEFAULT NULL,
    `supplier4partno`              VARCHAR(150) DEFAULT NULL,
    `supplier5`                    VARCHAR(100) DEFAULT NULL,
    `supplier5partno`              VARCHAR(150) DEFAULT NULL,
    `supplier6`                    VARCHAR(100) DEFAULT NULL,
    `supplier6partno`              VARCHAR(150) DEFAULT NULL,
    `componentlink1description`    VARCHAR(100) DEFAULT NULL,
    `componentlink1url`            VARCHAR(250) DEFAULT NULL,
    `componentlink2description`    VARCHAR(100) DEFAULT NULL,
    `supplier3partno`              VARCHAR(150) DEFAULT NULL,
    `componentlink2url`            VARCHAR(250) DEFAULT NULL,
    `componentlink3url`            VARCHAR(250) DEFAULT NULL,
    `componentlink4description`    VARCHAR(100) DEFAULT NULL,
    `componentlink4url`            VARCHAR(250) DEFAULT NULL,
    `componentlink5description`    VARCHAR(100) DEFAULT NULL,
    `componentlink5url`            VARCHAR(250) DEFAULT NULL,
    `componentlink6description`    VARCHAR(100) DEFAULT NULL,
    `componentlink6url`            VARCHAR(250) DEFAULT NULL,
    `footprintpath2`               VARCHAR(100) DEFAULT NULL,
    `footprintref2`                VARCHAR(100) DEFAULT NULL,
    `componentlink3description`    VARCHAR(100) DEFAULT NULL,
    `footprintpath3`               VARCHAR(100) DEFAULT NULL,
    `supplier3`                    VARCHAR(100) DEFAULT NULL,
    `supplier2`                    VARCHAR(100) DEFAULT NULL,
    `lastupdated`                  DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `archived`                     BIT          DEFAULT 0,
    `value`                        VARCHAR(100) DEFAULT NULL,
    `comment`                      VARCHAR(100) DEFAULT NULL,
    `manufacturerpartno`           VARCHAR(100) NOT NULL,
    `manufacturer`                 VARCHAR(100) NOT NULL,
    `description`                  VARCHAR(200) DEFAULT NULL,
    `price`                        VARCHAR(100) DEFAULT NULL,
    `lifecycle`                    VARCHAR(100) DEFAULT NULL,
    `supplier2partno`              VARCHAR(150) DEFAULT NULL,
    `series`                       VARCHAR(100) DEFAULT NULL,
    `footprintpath`                VARCHAR(100) DEFAULT NULL,
    `symbolref`                    VARCHAR(100) DEFAULT NULL,
    `symbolpath`                   VARCHAR(100) DEFAULT NULL,
    `devicepackage`                VARCHAR(100) DEFAULT NULL,
    `type`                         VARCHAR(100) DEFAULT NULL,
    `packaging`                    VARCHAR(100) DEFAULT NULL,
    `minimumorder`                 INT          DEFAULT 0,
    `supplier1`                    VARCHAR(100) DEFAULT NULL,
    `supplier1partno`              VARCHAR(150) DEFAULT NULL,
    `footprintref`                 VARCHAR(100) DEFAULT NULL,
    `footprintref3`                VARCHAR(100) DEFAULT NULL,
    `PartStatus`                   VARCHAR(127) DEFAULT NULL,
    `SupplierDevicePackage`        VARCHAR(127) DEFAULT NULL,
    `MountingType`                 VARCHAR(127) DEFAULT NULL,
    `OperatingTemperature`         VARCHAR(127) DEFAULT NULL,
    `PowerDissipationMax`          VARCHAR(127) DEFAULT NULL,
    `FETFeature`                   VARCHAR(127) DEFAULT NULL,
    `InputCapacitanceCissMaxVds`   VARCHAR(127) DEFAULT NULL,
    `VgsMax`                       VARCHAR(127) DEFAULT NULL,
    `PackageCase`                  VARCHAR(127) DEFAULT NULL,
    `GateChargeQgMaxVgs`           VARCHAR(127) DEFAULT NULL,
    `RdsOnMaxIdVgs`                VARCHAR(127) DEFAULT NULL,
    `DriveVoltageMaxRdsOnMinRdsOn` VARCHAR(127) DEFAULT NULL,
    `CurrentContinuousDrainId25C`  VARCHAR(127) DEFAULT NULL,
    `DraintoSourceVoltageVdss`     VARCHAR(127) DEFAULT NULL,
    `Technology`                   VARCHAR(127) DEFAULT NULL,
    `FETType`                      VARCHAR(127) DEFAULT NULL,
    `VgsthMaxId`                   VARCHAR(127) DEFAULT NULL,
    INDEX (`lastupdated`),
    INDEX (`archived`),
    INDEX (`manufacturerpartno`),
    PRIMARY KEY (`manufacturerpartno`, `manufacturer`)
) CHARACTER SET utf16
  COLLATE utf16_general_ci;


DROP VIEW IF EXISTS MOSFET_Discrete_N;

CREATE VIEW MOSFET_Discrete_N AS
SELECT `comment`                      AS `Comment`,
       `componentlink1description`    AS `ComponentLink1Description`,
       `componentlink1url`            AS `ComponentLink1URL`,
       `componentlink2description`    AS `ComponentLink2Description`,
       `componentlink2url`            AS `ComponentLink2URL`,
       `componentlink3description`    AS `ComponentLink3Description`,
       `componentlink3url`            AS `ComponentLink3URL`,
       `componentlink4description`    AS `ComponentLink4Description`,
       `componentlink4url`            AS `ComponentLink4URL`,
       `componentlink5description`    AS `ComponentLink5Description`,
       `componentlink5url`            AS `ComponentLink5URL`,
       `componentlink6description`    AS `ComponentLink6Description`,
       `componentlink6url`            AS `ComponentLink6URL`,
       `CurrentContinuousDrainId25C`  AS `Current - Continuous Drain (Id) @ 25°C`,
       `description`                  AS `Description`,
       `devicepackage`                AS `Device Package`,
       `DraintoSourceVoltageVdss`     AS `Drain to Source Voltage (Vdss)]`,
       `DriveVoltageMaxRdsOnMinRdsOn` AS `Drive Voltage (Max Rds On, Min Rds On)`,
       `FETFeature`                   AS `FET Feature`,
       `FETType`                      AS `FET Type`,
       `footprintpath`                AS `Footprint Path`,
       `footprintpath2`               AS `Footprint Path 2`,
       `footprintpath3`               AS `Footprint Path 3`,
       `footprintref`                 AS `Footprint Ref`,
       `footprintref2`                AS `Footprint Ref 2`,
       `footprintref3`                AS `Footprint Ref 3`,
       `GateChargeQgMaxVgs`           AS `Gate Charge (Qg) (Max) @ Vgs`,
       `InputCapacitanceCissMaxVds`   AS `Input Capacitance (Ciss) (Max) @ Vds`,
       `lastupdated`                  AS `LastUpdated`,
       `lifecycle`                    AS `Lifecycle Status`,
       `manufacturer`                 AS `Manufacturer`,
       `manufacturerpartno`           AS `Part Number`,
       `minimumorder`                 AS `Minimum Order`,
       `OperatingTemperature`         AS `Operating Temperature`,
       `PackageCase`                  AS `Package / Case`,
       `packaging`                    AS `Packaging`,
       `PartStatus`                   AS `Part Status`,
       `PowerDissipationMax`          AS `Power Dissipation (Max)`,
       `price`                        AS `Price`,
       `RdsOnMaxIdVgs`                AS `Rds On (Max) @ Id, Vgs`,
       `series`                       AS `Series`,
       `supplier1`                    AS `Supplier 1`,
       `supplier1partno`              AS `Supplier Part Number 1`,
       `supplier2`                    AS `Supplier 2`,
       `supplier2partno`              AS `Supplier Part Number 2`,
       `supplier3`                    AS `Supplier 3`,
       `supplier3partno`              AS `Supplier Part Number 3`,
       `supplier4`                    AS `Supplier 4`,
       `supplier4partno`              AS `Supplier Part Number 4`,
       `supplier5`                    AS `Supplier 5`,
       `supplier5partno`              AS `Supplier Part Number 5`,
       `supplier6`                    AS `Supplier 6`,
       `supplier6partno`              AS `Supplier Part Number 6`,
       `SupplierDevicePackage`        AS `Supplier Device Package`,
       `symbolpath`                   AS `Library Path`,
       `symbolref`                    AS `Library Ref`,
       `Technology`                   AS `Technology`,
       `type`                         AS `Type`,
       `value`                        AS `Value`,
       `VgsMax`                       AS `Vgs (Max)`,
       `VgsthMaxId`                   AS `Vgs(th) (Max) @ Id`

FROM t_MOSFET_Discrete t
where t.FETType = 'N-Channel';

DROP VIEW IF EXISTS MOSFET_Discrete_P;

CREATE VIEW MOSFET_Discrete_P AS
SELECT `comment`                      AS `Comment`,
       `componentlink1description`    AS `ComponentLink1Description`,
       `componentlink1url`            AS `ComponentLink1URL`,
       `componentlink2description`    AS `ComponentLink2Description`,
       `componentlink2url`            AS `ComponentLink2URL`,
       `componentlink3description`    AS `ComponentLink3Description`,
       `componentlink3url`            AS `ComponentLink3URL`,
       `componentlink4description`    AS `ComponentLink4Description`,
       `componentlink4url`            AS `ComponentLink4URL`,
       `componentlink5description`    AS `ComponentLink5Description`,
       `componentlink5url`            AS `ComponentLink5URL`,
       `componentlink6description`    AS `ComponentLink6Description`,
       `componentlink6url`            AS `ComponentLink6URL`,
       `CurrentContinuousDrainId25C`  AS `Current - Continuous Drain (Id) @ 25°C`,
       `description`                  AS `Description`,
       `devicepackage`                AS `Device Package`,
       `DraintoSourceVoltageVdss`     AS `Drain to Source Voltage (Vdss)]`,
       `DriveVoltageMaxRdsOnMinRdsOn` AS `Drive Voltage (Max Rds On, Min Rds On)`,
       `FETFeature`                   AS `FET Feature`,
       `FETType`                      AS `FET Type`,
       `footprintpath`                AS `Footprint Path`,
       `footprintpath2`               AS `Footprint Path 2`,
       `footprintpath3`               AS `Footprint Path 3`,
       `footprintref`                 AS `Footprint Ref`,
       `footprintref2`                AS `Footprint Ref 2`,
       `footprintref3`                AS `Footprint Ref 3`,
       `GateChargeQgMaxVgs`           AS `Gate Charge (Qg) (Max) @ Vgs`,
       `InputCapacitanceCissMaxVds`   AS `Input Capacitance (Ciss) (Max) @ Vds`,
       `lastupdated`                  AS `LastUpdated`,
       `lifecycle`                    AS `Lifecycle Status`,
       `manufacturer`                 AS `Manufacturer`,
       `manufacturerpartno`           AS `Part Number`,
       `minimumorder`                 AS `Minimum Order`,
       `OperatingTemperature`         AS `Operating Temperature`,
       `PackageCase`                  AS `Package / Case`,
       `packaging`                    AS `Packaging`,
       `PartStatus`                   AS `Part Status`,
       `PowerDissipationMax`          AS `Power Dissipation (Max)`,
       `price`                        AS `Price`,
       `RdsOnMaxIdVgs`                AS `Rds On (Max) @ Id, Vgs`,
       `series`                       AS `Series`,
       `supplier1`                    AS `Supplier 1`,
       `supplier1partno`              AS `Supplier Part Number 1`,
       `supplier2`                    AS `Supplier 2`,
       `supplier2partno`              AS `Supplier Part Number 2`,
       `supplier3`                    AS `Supplier 3`,
       `supplier3partno`              AS `Supplier Part Number 3`,
       `supplier4`                    AS `Supplier 4`,
       `supplier4partno`              AS `Supplier Part Number 4`,
       `supplier5`                    AS `Supplier 5`,
       `supplier5partno`              AS `Supplier Part Number 5`,
       `supplier6`                    AS `Supplier 6`,
       `supplier6partno`              AS `Supplier Part Number 6`,
       `SupplierDevicePackage`        AS `Supplier Device Package`,
       `symbolpath`                   AS `Library Path`,
       `symbolref`                    AS `Library Ref`,
       `Technology`                   AS `Technology`,
       `type`                         AS `Type`,
       `value`                        AS `Value`,
       `VgsMax`                       AS `Vgs (Max)`,
       `VgsthMaxId`                   AS `Vgs(th) (Max) @ Id`

FROM t_MOSFET_Discrete t
where t.FETType = 'P-Channel';
