CREATE TABLE z_CapacitorsCeramic
    (
        partid INT NOT NULL AUTO_INCREMENT,
        componentlink2url VARCHAR (250),
        componentlink3description VARCHAR (100),
        componentlink3url VARCHAR (250),
        componentlink4description VARCHAR (100),
        componentlink4url VARCHAR (250),
        componentlink5description VARCHAR (100),
        componentlink5url VARCHAR (250),
        componentlink6description VARCHAR (100),
        componentlink6url VARCHAR (250),
        footprintpath2 VARCHAR (100),
        footprintref2 VARCHAR (100),
        footprintpath3 VARCHAR (100),
        footprintref3 VARCHAR (100),
        componentlink2description VARCHAR (100),
        PartStatus VARCHAR (127),
        Tolerance VARCHAR (127),
        VoltageRated VARCHAR (127),
        TemperatureCoefficient VARCHAR (127),
        OperatingTemperature VARCHAR (127),
        Features VARCHAR (127),
        Ratings VARCHAR (127),
        Applications VARCHAR (127),
        FailureRate VARCHAR (127),
        MountingType VARCHAR (127),
        PackageCase VARCHAR (127),
        SizeDimension VARCHAR (127),
        HeightSeatedMax VARCHAR (127),
        ThicknessMax VARCHAR (127),
        capacitance VARCHAR (127),
        componentlink1url VARCHAR (250),
        componentlink1description VARCHAR (100),
        supplier6partno VARCHAR (150),
        lastupdated DATETIME,
        archived BIT,
        value VARCHAR (100),
        comment VARCHAR (100),
        manufacturerpartno VARCHAR (100),
        manufacturer VARCHAR (100),
        description VARCHAR (200),
        price VARCHAR (100),
        lifecycle VARCHAR (100),
        series VARCHAR (100),
        footprintref VARCHAR (100),
        footprintpath VARCHAR (100),
        symbolref VARCHAR (100),
        symbolpath VARCHAR (100),
        devicepackage VARCHAR (100),
        type VARCHAR (100),
        packaging VARCHAR (100),
        minimumorder INT,
        supplier1 VARCHAR (100),
        supplier1partno VARCHAR (150),
        supplier2 VARCHAR (100),
        supplier2partno VARCHAR (150),
        supplier3 VARCHAR (100),
        supplier3partno VARCHAR (150),
        supplier4 VARCHAR (100),
        supplier4partno VARCHAR (150),
        supplier5 VARCHAR (100),
        supplier5partno VARCHAR (150),
        supplier6 VARCHAR (100),
        LeadSpacing VARCHAR (127),
        LeadStyle VARCHAR (127),
        PRIMARY KEY (partid),
        INDEX (lastupdated, archived, manufacturerpartno)
    ) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
     	
CREATE VIEW 'CapacitorsCeramic_0603' AS SELECT * FROM z_CapacitorsCeramic t WHERE t.PackageCase='0603 (1608 Metric)';
CREATE VIEW 'CapacitorsCeramic_0805' AS SELECT * FROM z_CapacitorsCeramic t WHERE t.PackageCase='0805 (2012 Metric)';
CREATE VIEW 'CapacitorsCeramic_1206' AS SELECT * FROM z_CapacitorsCeramic t WHERE t.PackageCase='1206 (3216 Metric)';
CREATE VIEW 'CapacitorsCeramic_1210' AS SELECT * FROM z_CapacitorsCeramic t WHERE t.PackageCase='1210 (3225 Metric)';
CREATE VIEW 'CapacitorsCeramic_2220' AS SELECT * FROM z_CapacitorsCeramic t WHERE t.PackageCase='2220 (5750 Metric)';