"""empty message

Revision ID: 0304475cf682
Revises: c1a96ff8992d
Create Date: 2020-10-04 17:04:14.068544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0304475cf682'
down_revision = 'c1a96ff8992d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_category', 'inventory_category', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_category', type_='foreignkey')
    op.drop_column('inventory_category', 'parent_id')
    # ### end Alembic commands ###
