"""empty message

Revision ID: 284a437fe339
Revises: c30db6709fe2
Create Date: 2020-08-22 21:27:33.050841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284a437fe339'
down_revision = 'c30db6709fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrete_logic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logic_family', sa.String(length=30), nullable=True),
    sa.Column('logic_type', sa.String(length=30), nullable=True),
    sa.Column('number_of_bits', sa.String(length=30), nullable=True),
    sa.Column('propagation_delay', sa.String(length=30), nullable=True),
    sa.Column('supply_voltage_max', sa.String(length=30), nullable=True),
    sa.Column('supply_voltage_min', sa.String(length=30), nullable=True),
    sa.Column('logic_function', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('power_max', sa.String(length=30), nullable=True),
    sa.Column('vdrm', sa.String(length=30), nullable=True),
    sa.Column('current_rating', sa.String(length=30), nullable=True),
    sa.Column('dl_dt', sa.String(length=30), nullable=True),
    sa.Column('trigger_current', sa.String(length=30), nullable=True),
    sa.Column('latching_current', sa.String(length=30), nullable=True),
    sa.Column('holding_current', sa.String(length=30), nullable=True),
    sa.Column('gate_trigger_voltage', sa.String(length=30), nullable=True),
    sa.Column('emitter_forward_current', sa.String(length=30), nullable=True),
    sa.Column('emitter_forward_voltage', sa.String(length=30), nullable=True),
    sa.Column('triac_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triac')
    op.drop_table('discrete_logic')
    # ### end Alembic commands ###
