"""empty message

Revision ID: 51449b0556ba
Revises: 0304475cf682
Create Date: 2020-11-29 13:53:07.221531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51449b0556ba'
down_revision = '0304475cf682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_item', 'name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_item', 'name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
