"""empty message

Revision ID: 7e6770997013
Revises: 919a41af1b56
Create Date: 2020-07-26 20:57:24.767127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6770997013'
down_revision = '919a41af1b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oscillator_oscillator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_resonator', sa.String(length=30), nullable=True),
    sa.Column('current_supply_max', sa.String(length=30), nullable=True),
    sa.Column('frequency', sa.String(length=30), nullable=True),
    sa.Column('frequency_stability', sa.String(length=30), nullable=True),
    sa.Column('temperature_min', sa.String(length=30), nullable=True),
    sa.Column('temperature_max', sa.String(length=30), nullable=True),
    sa.Column('voltage_supply', sa.String(length=30), nullable=True),
    sa.Column('output_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oscillator_oscillator')
    # ### end Alembic commands ###
