"""empty message

Revision ID: 919a41af1b56
Revises: afe05e78ec30
Create Date: 2020-07-25 22:41:48.553542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919a41af1b56'
down_revision = 'afe05e78ec30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transistor_array_mosfet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_channels', sa.String(length=30), nullable=True),
    sa.Column('rds_on', sa.String(length=30), nullable=True),
    sa.Column('vgs_max', sa.String(length=30), nullable=True),
    sa.Column('vgs_th', sa.String(length=30), nullable=True),
    sa.Column('vds_max', sa.String(length=30), nullable=True),
    sa.Column('ids_max', sa.String(length=30), nullable=True),
    sa.Column('current_total_max', sa.String(length=30), nullable=True),
    sa.Column('power_max', sa.String(length=30), nullable=True),
    sa.Column('channel_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transistor_array_mosfet')
    # ### end Alembic commands ###
