"""empty message

Revision ID: a8376736e696
Revises: 574adfea93fe
Create Date: 2020-06-24 21:15:44.552515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8376736e696'
down_revision = '574adfea93fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_windings', sa.String(length=30), nullable=True),
    sa.Column('primary_dc_resistance', sa.String(length=30), nullable=True),
    sa.Column('secondary_dc_resistance', sa.String(length=30), nullable=True),
    sa.Column('tertiary_dc_resistance', sa.String(length=30), nullable=True),
    sa.Column('leakage_inductance', sa.String(length=30), nullable=True),
    sa.Column('primary_inductance', sa.String(length=30), nullable=True),
    sa.Column('secondary_current_rating', sa.String(length=30), nullable=True),
    sa.Column('tertiary_current_rating', sa.String(length=30), nullable=True),
    sa.Column('primary_voltage_rating', sa.String(length=30), nullable=True),
    sa.Column('secondary_voltage_rating', sa.String(length=30), nullable=True),
    sa.Column('tertiary_voltage_rating', sa.String(length=30), nullable=True),
    sa.Column('nps_turns_ratio', sa.String(length=30), nullable=True),
    sa.Column('npt_turns_ratio', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformer')
    # ### end Alembic commands ###
