"""empty message

Revision ID: c1a96ff8992d
Revises: 284a437fe339
Create Date: 2020-09-27 00:45:32.031539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a96ff8992d'
down_revision = '284a437fe339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('dici', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_inventory_location_dici'), 'inventory_location', ['dici'], unique=False)
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mpn', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('last_buy_price', sa.Float(), nullable=True),
    sa.Column('dici', sa.String(length=70), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_category.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpn', 'manufacturer', name='_mpn_manufacturer_item_uc')
    )
    op.create_index(op.f('ix_inventory_item_dici'), 'inventory_item', ['dici'], unique=False)
    op.create_index(op.f('ix_inventory_item_manufacturer'), 'inventory_item', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_inventory_item_mpn'), 'inventory_item', ['mpn'], unique=False)
    op.create_table('inventory_item_location_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actual_stock', sa.Float(), nullable=False),
    sa.Column('stock_min_level', sa.Float(), nullable=True),
    sa.Column('stock_notify_min_level', sa.Float(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_item_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=True),
    sa.Column('property_s_value', sa.String(length=100), nullable=True),
    sa.Column('property_i_value', sa.Integer(), nullable=True),
    sa.Column('property_f_value', sa.Float(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'property_name', name='_item_prop_uc')
    )
    op.create_index(op.f('ix_inventory_item_property_property_name'), 'inventory_item_property', ['property_name'], unique=False)
    op.create_table('inventory_item_location_stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_change', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_item_id'], ['inventory_item_location_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_item_location_stock_movement')
    op.drop_index(op.f('ix_inventory_item_property_property_name'), table_name='inventory_item_property')
    op.drop_table('inventory_item_property')
    op.drop_table('inventory_item_location_stock')
    op.drop_index(op.f('ix_inventory_item_mpn'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_manufacturer'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_dici'), table_name='inventory_item')
    op.drop_table('inventory_item')
    op.drop_index(op.f('ix_inventory_location_dici'), table_name='inventory_location')
    op.drop_table('inventory_location')
    op.drop_table('inventory_category')
    # ### end Alembic commands ###
