"""empty message

Revision ID: c30db6709fe2
Revises: e9d7c1747040
Create Date: 2020-08-22 00:45:39.531724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30db6709fe2'
down_revision = 'e9d7c1747040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opamp', sa.Column('number_of_channels', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opamp', 'number_of_channels')
    # ### end Alembic commands ###
