"""empty message

Revision ID: cdefc0f2a78f
Revises: a0dde78b6384
Create Date: 2020-06-04 00:12:38.911604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdefc0f2a78f'
down_revision = 'a0dde78b6384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('footprint_ref', sa.Column('storage_status', sa.Enum('NOT_STORED', 'STORING', 'STORED', 'STORAGE_FAILED', name='footprint_ref_storagestatus'), nullable=True))
    op.add_column('library_ref', sa.Column('storage_status', sa.Enum('NOT_STORED', 'STORING', 'STORED', 'STORAGE_FAILED', name='library_ref_storagestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_ref', 'storage_status')
    op.drop_column('footprint_ref', 'storage_status')
    # ### end Alembic commands ###
