"""empty message

Revision ID: f58558097ac2
Revises: a0dde78b6384
Create Date: 2020-06-07 17:54:06.833384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58558097ac2'
down_revision = 'a0dde78b6384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transducer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_magnitude', sa.String(length=50), nullable=True),
    sa.Column('output_type', sa.String(length=50), nullable=True),
    sa.Column('proportional_gain', sa.String(length=50), nullable=True),
    sa.Column('supply_voltage', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('footprint_ref', sa.Column('storage_status', sa.Enum('NOT_STORED', 'STORING', 'STORED', 'STORAGE_FAILED', name='footprint_ref_storagestatus'), nullable=True))
    op.add_column('library_ref', sa.Column('storage_status', sa.Enum('NOT_STORED', 'STORING', 'STORED', 'STORAGE_FAILED', name='library_ref_storagestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_ref', 'storage_status')
    op.drop_column('footprint_ref', 'storage_status')
    op.drop_table('transducer')
    # ### end Alembic commands ###
